_target_: autosim.experimental.simulations.GrossPitaevskiiEquation2D
return_timeseries: true
log_level: warning
n: 64
L: 10.0
T: 6.42
dt: 0.005
snapshot_dt: 0.02
skip_nt: 0.0
random_seed: 42
parameters_range:
  g: [0.0, 0.0]
  disorder_strength: [0.0, 0.0]
  spoon_strength: [0.0, 0.0]
  wx: [1.0, 1.0]
  wy: [1.0, 1.0]
  x0: [0.0, 0.0]
  y0: [1.5, 1.5]
  kx0: [0.0, 0.0]
  ky0: [-2.0, -2.0]
  width: [0.4, 0.4]
