_target_: autosim.experimental.simulations.GrayScott
return_timeseries: true
log_level: warning
n: 64
L: 1.0
T: 1280.0
dt: 1.0
snapshot_dt: 4.0
initial_condition: gaussians
fixed_parameters_given_pattern: true
pattern: spirals
# trajectory is rejected if the standard deviation of the 
# a simulated trajectory is less than min_std at any point in time
# across either of the output channels. The simulation 
# will automatically resimulate the data with the same 
# input parameters until the output trajectory has a std above the min_std value.
# Set to null to disable this check.
# This is done because trajectories with low std 
# harm the performance metrics during training. 
min_std: 0.01
